### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by fabpiaf** [UB-Mannheim/ocromore#5]
```
docker build -t ocromore .
...
Collecting scikit-bio>=0.5.1 (from -r ./tmp/requirements.txt (line 17))
  Downloading https://files.pythonhosted.org/packages/29/28/07326aa931c67d491d3053e2875b6c8f2904e661d9ab7c2840c3ae6b3780/scikit-bio-0.6.2.tar.gz (2.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e00dy152/scikit-bio/setup.py", line 26, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-e00dy152/scikit-bio/
The command '/bin/sh -c apt-get update && apt-get install --no-install-recommends -y   python3 python3-dev python3-pip python3-setuptools python3-tk python3-numpy   gcc git openssh-client libutf8proc-dev build-essential &&  pip3 install --upgrade wheel &&  pip3 install -r ./tmp/requirements.txt &&  mkdir -p /home/developer/coding/ocromore/ &&   cd /home/developer/coding/ &&  git clone https://github.com/eddieantonio/isri-ocr-evaluation-tools &&   cd isri-ocr-evaluation-tools &&  make &&   apt-get clean' returned a non-zero code: 1```

**Comment by JKamlah** [comment]
Hello @fabpiaf,
I've fixed the issue (Commit: 8d2ba28f376a6c5d98dae00f6ac9132e6d00e7b1) . Since the software is the outcome of a completed project, I have locked the Python library versions to ensure consistent results, just as when the original results were generated.
